import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F4F7FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerOscuro: {
    backgroundColor: '#0A1F44',
  },
  relojContainer: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    width: 'auto',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 999,
  },
  reloj: {
    fontSize: 32,
    display: 'flex',
    textAlign: 'center',
    fontFamily: 'Courier New',
    color: '#333F50',
    backgroundColor: '#B0C4DE',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
    fontWeight: 'bold',
  },
  relojOscuro: {
    color: '#33CFFF',
    backgroundColor: '#1E3A8A',
  },
  menuDesplegable: {
    marginTop: 10,
    backgroundColor: '#F4F7FA',
    borderRadius: 8,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  configuracionOscuro: {
    backgroundColor: '#0A1F44',
  },
  configuracionMenu: {
    marginBottom: 20,
  },
  iconoConfiguracion: {
    width: 40,
    height: 40,
  },
  titulo: {
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#333F50',
    marginBottom: 20,
  },
  tituloOscuro: {
    color: '#ffffff',
  },
  menuContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  boton: {
    backgroundColor: '#B0C4DE',
    width: 150,
    height: 150,
    borderRadius: 12,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    overflow: 'hidden',
    cursor: 'pointer',
    margin: 30,
    elevation: 9,
  },
  botonOscuro: {
    backgroundColor: '#B0C4DE',
    width: 150,
    height: 150,
    borderRadius: 12,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    overflow: 'hidden',
    cursor: 'pointer',
    margin: 30,
    elevation: 9,
  },
  icono: {
    width: 50,
    height: 50,
  },
  crucetaContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  crucetaFila: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '60%',
    marginVertical: 10,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0A1F44',
  },
  parametroContainer: {
    width: 300,
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    alignItems: 'center',
  },
  parametroTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  input: {
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
    paddingHorizontal: 10,
    width: '100%',
  },
  qrContainer: {
    width: 300,
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    alignItems: 'center',
  },
  qrTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  camera: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  cameraText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
  },
});

export default styles;